---
- name: Converge
  hosts: all
  become: true

  vars:
    - docker_mocker: true
    - container_run_as_service: true
    - container_privileged: true
    - docker_containers:
        - name: ubuntu-container
          image: geerlingguy/docker-ubuntu1804-ansible
          expose:
            - "8080"
          ports:
            - "2200:22"
            - "8081:8080"
          volumes:
            - "/sys/fs/cgroup:/sys/fs/cgroup"
          ulimits:
            - "nofile=40000:40000"
        - name: centos-container
          image: geerlingguy/docker-centos7-ansible
          expose:
            - "8080"
          ports:
            - "2222:22"
            - "8082:8080"
          volumes:
            - "/sys/fs/cgroup:/sys/fs/cgroup"

  roles:
    - ansible-role-docker
